/**
 * DO NOT EDIT THIS FILE.
 *
 * This source code was autogenerated from source code within the `app/src/gms` directory
 * and is not intended for modifications. If any edits should be made, please do so in the
 * corresponding file under the `app/src/gms` directory.
 */
/*
 * Copyright 2018 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.example.kotlindemos

import androidx.appcompat.app.AppCompatActivity


/**
 * A simple POJO that holds the details about the demo that are used by the List Adapter.
 *
 * @property titleId the resource id of the title of the demo.
 * @property descriptionId the resources id of the description of the demo.
 * @property activityClass the demo activity's class.
 */
data class DemoDetails(val titleId: Int, val descriptionId: Int,
                       val activityClass: Class<out AppCompatActivity>)
