/**
 * DO NOT EDIT THIS FILE.
 *
 * This source code was autogenerated from source code within the `app/src/gms` directory
 * and is not intended for modifications. If any edits should be made, please do so in the
 * corresponding file under the `app/src/gms` directory.
 */
// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
package com.example.kotlindemos

import android.os.Bundle
import android.view.View
import android.widget.CheckBox
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import com.google.android.libraries.maps.StreetViewPanorama
import com.google.android.libraries.maps.SupportStreetViewPanoramaFragment
import com.google.android.libraries.maps.model.LatLng
import com.google.android.libraries.maps.model.StreetViewSource


/**
 * This shows how to create an activity with static streetview (all options have been switched off)
 */
class StreetViewPanoramaOptionsDemoActivity : AppCompatActivity() {
    private var streetViewPanorama: StreetViewPanorama? = null
    private lateinit var streetNameCheckbox: CheckBox
    private lateinit var navigationCheckbox: CheckBox
    private lateinit var zoomCheckbox: CheckBox
    private lateinit var panningCheckbox: CheckBox
    private lateinit var outdoorCheckbox: CheckBox

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(com.example.common_ui.R.layout.street_view_panorama_options_demo)
        streetNameCheckbox = findViewById(com.example.common_ui.R.id.streetnames)
        navigationCheckbox = findViewById(com.example.common_ui.R.id.navigation)
        zoomCheckbox = findViewById(com.example.common_ui.R.id.zoom)
        panningCheckbox = findViewById(com.example.common_ui.R.id.panning)
        outdoorCheckbox = findViewById(com.example.common_ui.R.id.outdoor)
        val streetViewPanoramaFragment =
            supportFragmentManager.findFragmentById(com.example.common_ui.R.id.streetviewpanorama) as SupportStreetViewPanoramaFragment?
        streetViewPanoramaFragment?.getStreetViewPanoramaAsync { panorama: StreetViewPanorama ->
            streetViewPanorama = panorama
            panorama.isStreetNamesEnabled = streetNameCheckbox.isChecked()
            panorama.isUserNavigationEnabled = navigationCheckbox.isChecked()
            panorama.isZoomGesturesEnabled = zoomCheckbox.isChecked()
            panorama.isPanningGesturesEnabled = panningCheckbox.isChecked()

            // Only set the panorama to SAN_FRAN on startup (when no panoramas have been
            // loaded which is when the savedInstanceState is null).
            savedInstanceState ?: setPosition()
        }
    }

    private fun setPosition() {
        streetViewPanorama?.setPosition(
            SAN_FRAN,
            RADIUS,
            if (outdoorCheckbox.isChecked) StreetViewSource.OUTDOOR else StreetViewSource.DEFAULT
        )
    }

    private fun checkReady(): Boolean {
        if (streetViewPanorama == null) {
            Toast.makeText(this, com.example.common_ui.R.string.map_not_ready, Toast.LENGTH_SHORT).show()
            return false
        }
        return true
    }

    fun onStreetNamesToggled(view: View?) {
        if (!checkReady()) {
            return
        }
        streetViewPanorama?.isStreetNamesEnabled = streetNameCheckbox.isChecked
    }

    fun onNavigationToggled(view: View?) {
        if (!checkReady()) {
            return
        }
        streetViewPanorama?.isUserNavigationEnabled = navigationCheckbox.isChecked
    }

    fun onZoomToggled(view: View?) {
        if (!checkReady()) {
            return
        }
        streetViewPanorama?.isZoomGesturesEnabled = zoomCheckbox.isChecked
    }

    fun onPanningToggled(view: View?) {
        if (!checkReady()) {
            return
        }
        streetViewPanorama?.isPanningGesturesEnabled = panningCheckbox.isChecked
    }

    fun onOutdoorToggled(view: View?) {
        if (!checkReady()) {
            return
        }
        setPosition()
    }

    companion object {
        // Cole St, San Fran
        private val SAN_FRAN = LatLng(37.765927, -122.449972)
        private const val RADIUS = 20
    }
}